version: "2"

linters:
  default: standard
  disable:
    - errcheck

formatters:
  enable:
    - goimports
    - golines
  settings:
    golines:
      max-len: 100
      shorten-comments: true

run:
  timeout: 5m
