= Packer Plugin Oxide

The https://oxide.computer[Oxide] multi-component plugin can be
used with HashiCorp (IBM) Packer to create custom Oxide images. The
https://developer.hashicorp.com/packer/integrations/oxidecomputer/oxide[documentation]
describes the plugin and its components.

== Installation

=== Install Using Packer

Refer to the installation instructions in the
https://developer.hashicorp.com/packer/integrations/oxidecomputer/oxide[documentation].

=== Manual Installation

Pre-built releases are located on the
https://github.com/oxidecomputer/packer-plugin-oxide/releases[GitHub
releases] page. Download the release for your target platform and unarchive
it to retrieve the plugin binary. Install the plugin binary by following the
https://developer.hashicorp.com/packer/docs/plugins/install[Installing Plugins]
documentation.

=== Build from Source

Clone the GitHub repository locally and run `make build` to build
the plugin for your target platform. Upon successful compilation,
a `packer-plugin-oxide` plugin binary can be found in the root
of this repository. Install the plugin binary by following the
https://developer.hashicorp.com/packer/docs/plugins/install[Installing Plugins]
documentation.

== Usage

Refer to the example configuration in link:example[`example`] or the 
https://developer.hashicorp.com/packer/integrations/oxidecomputer/oxide[documentation]
for usage information.

The documentation is populated from the content in link:.web-docs[`.web-docs`]
which is rendered from the raw documentation in link:docs[`docs`].

== Contributing

Read link:CONTRIBUTING.adoc[`CONTRIBUTING.adoc`] for development information.
