---
on:
  push:
    tags:
     - "v[0-9]+.[0-9]+.[0-9]+"
  workflow_dispatch:
    inputs:
      version:
        description: "Version to deploy (e.g., v1.2.3)."
        required: true

permissions:
  contents: write

name: Release

# Don't run multiple releases at the same time.
concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: false

jobs:
  version:
    name: Configure Version
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.output_version.outputs.version }}
    steps:
      - name: Validate Version
        if: github.event_name == 'workflow_dispatch'
        run: |
          if [[ ! "${{ github.event.inputs.version }}" =~ ^v[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
            echo "Error: Version must follow the format vX.Y.Z (e.g., v1.0.0)."
            exit 1
          fi

          echo "Version is valid: ${{ github.event.inputs.version }}"

      - name: Output Version
        id: output_version
        run: |
          if [[ "${{ github.event_name }}" == "push" ]]; then
            VERSION=${GITHUB_REF_NAME}
            echo "version=$VERSION" >> $GITHUB_OUTPUT
          elif [[ "${{ github.event_name }}" == "workflow_dispatch" ]]; then
            VERSION=${{ github.event.inputs.version }}
            echo "version=$VERSION" >> $GITHUB_OUTPUT
          else
            echo "Error: Unsupported event type."
            exit 1
          fi

  release:
    name: Run Release
    runs-on: ubuntu-latest
    needs: [version]
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          ref: ${{ needs.version.outputs.version }}
          fetch-depth: 0

      - name: Install Go
        uses: actions/setup-go@v5
        with:
          go-version-file: "go.mod"

      - name: Describe Plugin
        id: plugin_describe
        run: echo "api_version="$(go run . describe | jq -r '.api_version')" >> $GITHUB_OUTPUT"

      # TODO: Configure signing.
      # - name: Import GPG key
      #   id: import_gpg
      #   uses: crazy-max/ghaction-import-gpg@v5
      #   with:
      #     gpg_private_key: ${{ secrets.GPG_PRIVATE_KEY }}
      #     passphrase: ${{ secrets.GPG_PASSPHRASE }}

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v6.1.0
        with:
          version: "~> v2"
          args: release --clean
        env:
          API_VERSION: ${{ steps.plugin_describe.outputs.api_version }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          # TODO: Configure signing.
          # GPG_FINGERPRINT: ${{ steps.import_gpg.outputs.fingerprint }}
