---
name: Test Example Configuration

on:
  workflow_dispatch:
    inputs:
      packer_log:
        description: "Value for PACKER_LOG."
        required: false
        default: "0"
      working_directory:
        description: "Working directory containing Packer configuration to test."
        required: false
        default: "./example"

permissions:
  contents: read

jobs:
  packer:
    runs-on: ubuntu-latest
    name: Run Packer
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Packer
        uses: hashicorp/setup-packer@main
        with:
          version: latest

      - name: Init
        run: packer init .
        working-directory: ${{ github.event.inputs.working_directory }}

      - name: Validate
        run: packer validate .
        working-directory: ${{ github.event.inputs.working_directory }}
        env:
          PACKER_LOG: ${{ github.event.inputs.packer_log}}
          OXIDE_HOST: ${{ secrets.OXIDE_HOST }}
          OXIDE_TOKEN: ${{ secrets.OXIDE_TOKEN }}

      - name: Build
        run: packer build .
        working-directory: ${{ github.event.inputs.working_directory }}
        env:
          PACKER_LOG: ${{ github.event.inputs.packer_log}}
          OXIDE_HOST: ${{ secrets.OXIDE_HOST }}
          OXIDE_TOKEN: ${{ secrets.OXIDE_TOKEN }}
